server:
  port: 3344

spring:
  application:
    name: beHealthy-config-server-3344
  cloud:
    config:
     server:
       git:
         uri: https://github.com/Joshioner/beHealthy-config-server.git   #远程仓库url地址